-- ========================================================
-- TABLAS DE NEGOCIO: ROLES, EMPLEADOS Y CLIENTES
-- Copiar y pegar en: Supabase -> SQL Editor -> Run
-- ========================================================

-- 1. Tabla de Roles (Puestos y Salarios)
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  departamento TEXT NOT NULL,
  salario NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Empleados
CREATE TABLE IF NOT EXISTS empleados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  rol_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
  fecha_ingreso DATE DEFAULT CURRENT_DATE,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Clientes (CONFIDENCIAL: El chat NO tiene acceso)
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  empresa TEXT NOT NULL,
  email TEXT NOT NULL,
  saldo_pendiente NUMERIC(10, 2) DEFAULT 0.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Datos de Prueba Iniciales
INSERT INTO roles (nombre, departamento, salario) VALUES
  ('Desarrollador Fullstack', 'Tecnología', 3200.00),
  ('Ingeniero de IA', 'Tecnología', 4500.00),
  ('Especialista de Soporte', 'Operaciones', 1800.00),
  ('Líder de Recursos Humanos', 'RRHH', 2800.00)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO empleados (nombre, email, rol_id, fecha_ingreso) VALUES
  ('Carlos Mendoza', 'carlos.m@novatech.com', 1, '2023-03-15'),
  ('Lucía Gómez', 'lucia.g@novatech.com', 2, '2022-08-01'),
  ('Andrés Silva', 'andres.s@novatech.com', 3, '2024-01-10'),
  ('Mariana Torres', 'mariana.t@novatech.com', 4, '2021-05-20')
ON CONFLICT (email) DO NOTHING;

INSERT INTO clientes (nombre, empresa, email, saldo_pendiente) VALUES
  ('Banco Futuro S.A.', 'Banco Futuro', 'contacto@bancofuturo.com', 15000.00),
  ('Retail Global Corp', 'Retail Global', 'compras@retailglobal.com', 8500.00);
